---
title: StayClassy
timezone: UTC
collections:
  featured_categories:
    title: Featured Categories
    output: true
    permalink: "/category/:name/"
  featured_tags:
    title: Featured Tags
    output: true
    permalink: "/tag/:name/"
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/projects/:path/"
  uploads:
    title: Uploads
    output: true
url: https://stayclassy.gr
baseurl: 
tagline: Stay classy my dear!
description: Beauty, Humour and Inspiration
author:
  name: Emily Papazhsh
  email: emilypap.16@gmail.com
image: "/uploads/main-img.jpg"
color: "#4f86aa"
google_fonts: Roboto+Slab:700|Noto+Serif:400,400i,700,700i
font_heading: "'Roboto Slab', Helvetica, Arial, sans-serif"
font: "'Noto Serif', Georgia, serif"
google_analytics: UA-69030775-3
disqus_shortname: yet-another-blog
copyright: "© 2018. All rights reserved."
permalink: "/:categories/:title.html"
paginate: 5
paginate_path: "/page-:num/"
gems:
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate
- jekyll-redirect-from
exclude:
- README.md
- LICENSE.md
- node_modules
- package.json
- Gemfile
- Gemfile.lock
kramdown:
  footnote_backlink: "&#x21a9;&#xfe0e;"
  math_engine: mathjax
  math_engine_opts:
    preview: true
    preview_as_code: true
compress_html:
  comments:
  - "<!--"
  - "-->"
  clippings: all
  endings: all
  ignore:
    envs:
    - development
sass:
  style: compressed
